import math, time

def get_L(up):
    lis = [0 for i in range(up + 1)]
    for m in range(2, int((up / 2) ** 0.5) + 1):
        for n in range(1, m):
            # The triple generated by Euclid's formula is primitive if and only if
            # m and n are coprime and
            # not both odd.
            if math.gcd(m, n) == 1 and (n + m) % 2 == 1:
                a = m * m + n * n
                b = m * m - n * n
                c = 2 * m * n
                L = a + b + c
                while L <= up:
                    lis[L] += 1
                    L += a + b + c
    return lis

t1 = time.time()

temp, count = get_L(1500000), 0
for i in temp:
    count += 1 if i == 1 else 0

t2 = time.time()
print("answer is: ", count, "time spent:", t2 - t1)

